theme = "gruvbox"
[editor]
line-number = "relative"
scroll-lines = 1

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true

[keys.normal]
P = "paste_after"
c = "change_selection_noyank"
d = "delete_selection_noyank"
esc = ["collapse_selection", "keep_primary_selection"]
p = "paste_before"
"Ć" = "copy_selection_on_prev_line"

[keys.normal.space]
Z = ":set-option gutters.layout []"
q = ":q"
w = ":w"
z = ":set-option gutters.layout [\"diagnostics\",\"spacer\",\"line-numbers\",\"spacer\",\"diff\"]"

